### PR TITLE
Casting date index to datetime

### PR DESCRIPTION
**Pull request by tuxskar**
I have noticed that using the DateFrame by default is not casting the index to datetime so using the next code as a sample
```python
from alpha_vantage.cryptocurrencies import CryptoCurrencies

crypto = CryptoCurrencies(key=ALPHAVANTAGE_API_KEY, output_format='pandas')
data, meta_data = crypto.get_digital_currency_intraday('BTC', 'EUR')
data['1a. price (EUR)'].plot()
plt.title(f'{meta_data["1. Information"]} {meta_data["3. Digital Currency Name"]}')
plt.show()
```
You would get this image:
image

With this pull request the same code will create this other image:
image

Where the X axis is populated with the dates correctly

### CODE REVIEW

**Comment by tuxskar** [comment]
Checking on the issues tracker I have found that this issue was reported in #73 and #79. 
I hope this pull request helps.

**Comment by RomelTorres** [comment]
Hola @tuxskar , good job on the pull requests. It probably helps (i am not using the library myself at the moment) I'll leave the pull request open for a while so people can comment on it.  There is an unittest failing: test_time_series_intraday_date_indexing, can you fix that too.
Muchas gracias por la contribución a la libreria.
Romel

**Comment by AngelLomeli** [comment]
@tuxskar I just started looking into this project as well. I stumbled upon a one-liner that does the same thing before I saw your pull request here.

`data.set_index( to_datetime(data.index), inplace=True )`

This came from https://chrisalbon.com/python/data_wrangling/pandas_time_series_basics/ , and so far I've played around using the get_intraday, get_daily, and get_weekly calls.

I think it's pretty much the same under the hood, but I thought I would share it as a possible alternative.

**Comment by tuxskar** [comment]
Hi @AngelLomeli ,

Thank you very much for your suggestion, I added the code in the way you commented because it is more elegant and I like it more.

Also, I have updated the failing test that was checking for the index to be string type while after applying this changes the index is not string anymore but `pandas.Timestamp` type. 

I don't really see why it was the check for the index as string so now it is checking if they are `pandas.Timestamp` type

**Comment by tuxskar** [comment]
@RomelTorres did you have the chance to take a look on the changes I made to this commit to avoid the conflicts and the test updates?

**Comment by langarus** [comment]
@AngelLomeli  and @tuxskar I've used 
`data.set_index( to_datetime(data.index), inplace=True )`

But the problem I have now is that it displays the trading which happens after market close, and the Vantage API does not have those dates, and results in an awkward looking chart. Do you know any way to change that?

**Comment by Vidhin05** [comment]
@AngelLomeli @tuxskar I get the same problem as @langarus. Any fix?

**Comment by langarus** [comment]
The only way around this was to not show the date. Or there's a workaround (didn't do it personally) where you can force it manually to have all numbers the same size.

**Comment by nocluebutalotofit** [comment]
> 
> 
> @AngelLomeli and @tuxskar I've used
> `data.set_index( to_datetime(data.index), inplace=True )`
> 
> But the problem I have now is that it displays the trading which happens after market close, and the Vantage API does not have those dates, and results in an awkward looking chart. Do you know any way to change that?
> 
> 

You can set:
ts.indexing_type = 'integer'
and the x axis will contract the overnight gaps.

**Comment by PatrickAlphaVantage** [comment]
Hey everyone, I'm jumping on to help out. Romel has been pretty swamped. I'm going to close this PR in a few weeks unless someone else wants to jump on. @tuxskar - is this still a feature we want to put in? I'm just catching up...

**Comment by PatrickAlphaVantage** [comment]
I'm going to remove this PR as of no activity

**Pull request closed without merging**
