### PR TITLE
Added 'month' parameter support for intraday data endpoints

### PR DESCRIPTION
**Pull request by masonJamesWheeler**
Alpha Vantage recently discontinued their `intraday_extended` and introduced a 'month' parameter to their time-series and indicator data endpoints. This pull request updates the Python wrapper accordingly.

Changes include:
- Update to support the 'month' parameter for intraday data fetching.
- Users can now input a month in the format "YYYY-MM" to fetch corresponding intraday data.
- Necessary adjustments to the relevant functions and methods.

This update should align the wrapper with the latest changes in Alpha Vantage's API and improve the overall user experience.

### CODE REVIEW

**Comment by am1ter** [comment]
@masonJamesWheeler, hello! Thank you for the PR. I was considering creating my own, but I noticed that you have already created one.

By the way, I took a look at your commit and discovered that it includes a broken file rename, resulting in a broken git history. Could you please revise your commit to fix this issue? I'm concerned that the maintainers might not merge the PR if the history remains broken.

Moreover, TIME_SERIES_INTRADAY_EXTENDED function is depreciated, so `TimeSeries.get_intraday_extended()` method should be removed or marked as depreciated.

**Comment by masonJamesWheeler** [comment]
Thankyou! Working on it now.

From: Aleksei Semenov ***@***.***>
Date: Sunday, July 16, 2023 at 12:40 PM
To: RomelTorres/alpha_vantage ***@***.***>
Cc: Mason J. Wheeler ***@***.***>, Mention ***@***.***>
Subject: Re: [RomelTorres/alpha_vantage] Added 'month' parameter support for intraday data endpoints (PR #348)

@masonJamesWheeler<https://urldefense.com/v3/__https:/github.com/masonJamesWheeler__;!!K-Hz7m0Vt54!kwe9uV_KvMA7FkOl6VwhBpnymvCiqIbgOI1EQcO2q_xKRshL8S8S_FAZEL_70SmEXRIwVxkhE42MR-EW74CgZA$>, hello! Thank you for the PR. I was considering creating my own, but I noticed that you have already created one.

By the way, I took a look at your commit and discovered that it includes a broken file rename, resulting in a broken git history. Could you please revise your commit to fix this issue? I'm concerned that the maintainers might not merge the PR if the history remains broken.

Moreover, TIME_SERIES_INTRADAY_EXTENDED function is depreciated, so TimeSeries.get_intraday_extended() method should be removed or marked as depreciated.

**Comment by seanbearden** [comment]
@masonJamesWheeler Thanks for this! I would love to see this merged.

**Comment by AlphaVantageSupport** [comment]
This can be implemented via the 3.0.0 launch in July 2024. Thanks!

**Pull request closed without merging**
