### PR TITLE
Adding crypto-rating functionality

### PR DESCRIPTION
**Pull request by rxmxn**
Adding crypto-rating functionality and removing the get_digital_currency_exchange_rate that would be just a repetition of the CURRENCY_EXCHANGE_RATE one and it doesn't work anyways since it's referencing that function with the wrong arguments.

### CODE REVIEW

**Comment by rxmxn** [comment]
#231

**Comment by PatrickAlphaC** [comment]
Thanks for this PR! I think it would make sense to still have both even though they are duplicitous. The addition of the crypto-rating is great! Would you like to change your PR to fix the `get_digital_crypto_rating` method?

**Comment by rxmxn** [comment]
Hi Patrick. Sure, let me do another commit with the changes

**Comment by rxmxn** [comment]
Done. Let me know if it looks ok to you 👍

**Comment by PatrickAlphaC** [comment]
This looks great :) Thank you!

**Pull request merged**
