### PR TITLE
support for news and sentiments

### PR DESCRIPTION
**Pull request by usapkota**
Adding support for News and Sentiments (Within Alpha Intelligence). Also adding a parameter to say No to indexing within AlphaVantage when the data is pandas dataframe.

### CODE REVIEW

**Comment by scottstables** [comment]
Wonderful - Can you provide an example on how to use the News and Sentiments functions ?

**Comment by scottstables** [comment]
I'm using this - but the returned data from the function is NOT a dataframe... it seems to be an un-even tuple ?

**Comment by usapkota** [comment]
image

**Comment by usapkota** [comment]
image

**Comment by usapkota** [comment]
Other functions might not be working because there seems to be some issue with the api, even the example is not working: 

image
https://www.alphavantage.co/documentation/#gainer-loser

**Comment by usapkota** [comment]
@AlphaVantageSupport Can we have this merged to develop branch?

**Comment by usapkota** [comment]
Here is an example code.

image

**Comment by NolanEssertaize** [comment]
Hello, where did you find theses module(alpha_vantage one), is it with the premium subscriptions  ?

**Comment by AlphaVantageSupport** [comment]
This can be implemented via the 3.0.0 launch in July 2024. Thanks!

**Pull request closed without merging**
