### PR TITLE
add intraday-extended endpoint

### PR DESCRIPTION
**Pull request by atarax**

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Nice PR! Could you add some tests to this?

**Review by PatrickAlphaC — APPROVED** [review]

**Comment by kaessert** [comment]
Thanks! I guess i could :) Can you give me a hint how to execute the tests?

**Comment by kaessert** [comment]
nevermind, i found out :)

**Comment by PatrickAlphaC** [comment]
Got it, thank you for this PR!

**Comment by kaessert** [comment]
Happy to contribute!

**Pull request merged**
