### PR TITLE
Master Upgrade

### PR DESCRIPTION
**Pull request by PatrickAlphaVantage**
Release 2.5

Hi Romel!
This repo is awesome. I was wondering two things:

1. Could we do an update of master?
2. I noticed you're not using this repo much anymore. Could we give me write permissions so that you don't feel burdened to keep up to date with it? Thank you!

### CODE REVIEW

**Comment by RomelTorres** [comment]
Let me know if you got the invite :)

**Comment by PatrickAlphaVantage** [comment]
Got it :D

Woot woot! Thank you!

**Comment by PatrickAlphaVantage** [comment]
> Got it :D Woot woot! Thank you!
> […](#)
> Sent from my iPhone
> On Sep 11, 2019, at 1:17 PM, Romel Torres ***@***.***> wrote: Let me know if you got the invite :) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

@RomelTorres 
Hmmm, do you think you could take a look at this too? I'll jump on more PRs moving forward :)

**Comment by PatrickAlphaVantage** [comment]
:D

**Pull request merged**
